In [1]:
import pandas as pd
import pickle

In [2]:
dtypes = {
    'ip': 'uint32',
    'app': 'uint16',
    'device': 'uint16',
    'os': 'uint16',
    'channel': 'uint16',
    'is_attributed': 'uint8',
    'click_id': 'uint32'
}

In [3]:
train_supplement_df = pd.read_hdf('../tamaki_script/X_train_add_supplement.h5', 'table')
with open('../data/pickle/add_rolling_and_diff_feature.pkl', mode='rb') as f:
    rolling_df = pickle.load(f)
train_supplement_df.click_time = pd.to_datetime(train_supplement_df.click_time, unit='s')

In [4]:
train_supplement_df = pd.merge(train_supplement_df, rolling_df[['ip', 'click_time', 'window_count']], on=[
    'ip', 'click_time'], how='left')

In [5]:
train_supplement_df = train_supplement_df.drop_duplicates()

In [6]:
train_supplement_df.head()

,app,attributed_time,channel,click_id,click_time,device,ip,is_attributed,os,day,...,ip_device_count,app_channel_count,ip_day_hour_channel_count,nextClick,ip_channel_unique,ip_app_unique,ip_device_os_app_unique,ip_device_unique,app_channel_unique,window_count
0,3,NaN,379,NaN,2017-11-06 14:32:21,1,83230,0.0,13,6,...,32464,1314929,1,5340.0,141,90,51,30,50,1.0
1,3,NaN,379,NaN,2017-11-06 14:33:34,1,17357,0.0,19,6,...,30556,1314929,1,5547.0,137,81,48,29,50,1.0
2,3,NaN,379,NaN,2017-11-06 14:34:12,1,35810,0.0,13,6,...,10975,1314929,1,5925.0,139,73,42,19,50,1.0
3,14,NaN,478,NaN,2017-11-06 14:34:52,1,45745,0.0,13,6,...,193613,24090,1,5110.0,152,164,63,122,40,1.0
4,3,NaN,379,NaN,2017-11-06 14:35:08,1,161007,0.0,13,6,...,1165,1314929,1,33756.0,94,38,28,5,50,1.0

In [9]:
train_supplement_df.to_hdf("X_train_add_supplement_add_rolling.h5", 'table',
            complib='blosc', complevel=9)

/home/yoshikawa/.pyenv/versions/3.6.4/lib/python3.6/site-packages/pandas/core/generic.py:1471: PerformanceWarning:
your performance may suffer as PyTables will pickle object types that it cannot
map directly to c-types [inferred_type->mixed,key->block4_values] [items->['attributed_time']]

  return pytables.to_hdf(path_or_buf, key, self, **kwargs)